# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Promotion PR

on:
  push:
    branches:
      - dev
      - stage

permissions:
  contents: read
  pull-requests: write

jobs:
  promotion-pr:
    name: Promotion PR
    uses: kirchDev/workflows/.github/workflows/_promotion-pr.yml@ea3a3c15385340fe1f9751e0afefaef32970aad7 # v0.12.0
